# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:very_good_analysis/analysis_options.yaml

plugins:
  riverpod-lint:
    version: ^3.1.3
    diagnostics:
      missing_provider_scope: true
      provider_dependencies: true
      scoped_providers_should_specify_dependencies: true
      avoid_build_context_in_providers: true
      provider_parameters: true
      avoid_public_notifier_properties: true
      unsupported_provider_value: true
      functional_ref: true
      notifier_extends: true
      avoid_ref_inside_state_dispose: true
      avoid_keep_alive_dependency_inside_auto_dispose: true
      notifier_build: true
      riverpod_syntax_error: true
      async_value_nullable_pattern: true
      protected_notifier_properties: true

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart.dev/tools/linter-rules
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
    sort_constructors_first: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
