name: raspberry_lights_controller
description: An app for controlling the light pattern run by a Raspberry Pi.

version: 0.4.0

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3
  recase: ^4.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/launch_icon_v2.png"
  adaptive_icon_background: "#FF303030"
  adaptive_icon_foreground: "assets/launch_icon_foreground_v2.png"
