name: raspberry_lights_controller
description: An app for controlling the light pattern run by a Raspberry Pi.

version: 0.2.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  recase: ^4.1.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.1.1
  # TODO: make a custom colopicker, neither of these are quite right for this
  flutter_colorpicker: ^1.0.2
  flex_color_picker: 2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/launch_icon_v2.png"
  adaptive_icon_background: "#FF303030"
  adaptive_icon_foreground: "assets/launch_icon_foreground_v2.png"
